### ISSUE TITLE
Missing error checks

### ISSUE THREAD

**Issue by aarondl** [cloudfoundry/mariadb_ctrl#4]
It's possible the cmd.Start can return an error (missing binary, missing file permissions). This error should probably be returned to the caller and not ignored. If it's intentional that it's ignored it should look like:

```go
_ = cmd.Start()
```

This stops linters from complaining about it.

https://github.com/cloudfoundry/mariadb_ctrl/blob/eb8cc58ba0312a489280cf88923aa50af7b29b41/os_helper/os_helper.go#L78
https://github.com/cloudfoundry/mariadb_ctrl/blob/eb8cc58ba0312a489280cf88923aa50af7b29b41/os_helper/os_helper.go#L54

**Comment by robdimsdale** [comment]
@aarondl thanks for this. If this is causing you an issue, please feel free to submit a PR. Otherwise we will fix this when we next spend time in this codebase.

**Comment by robdimsdale** [comment]
Closing this issue as there's been no response in a week. Please feel free to reopen or submit a PR.

**Comment by aarondl** [comment]
I hadn't responded since it sounded like filing the issue had the desired effect; you said you'd fix it when you next spent time in the codebase. That was good enough for me :)
